# Generated by Django 5.0.4 on 2024-04-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('own_invite_code', models.CharField(max_length=6)),
                ('friends_invite_code', models.CharField(max_length=6)),
            ],
        ),
    ]
