# Generated by Django 5.0.4 on 2024-04-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends_invite_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='own_invite_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
